version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mv target/polifono-*.war target/ROOT.war

artifacts:
  base-directory: target
  files:
    - ROOT.war

cache:
  paths:
    - /root/.m2/**/*
