version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - cp target/polifono-*.jar ./deployment.jar
      - ls -la
artifacts:
  files:
    - deployment.jar
    - .platform/**
    - .platform/**/*
  name: polifono.zip
cache:
  paths:
    - /root/.m2/**/*
