version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mv target/polifono-*.jar target/ROOT.jar
      - mkdir -p output
      - cp target/ROOT.jar output/
      - cp -r .ebextensions output/

artifacts:
  base-directory: output
  files:
    - ROOT.jar
    - .ebextensions/**

cache:
  paths:
    - /root/.m2/**/*
