version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p deploy
      - cp target/polifono-*.jar ./deploy
      - ls -la
      - cp -r .ebextensions ./deploy
      - ls -la deploy
artifacts:
  files:
    - deploy/**
    - deploy/.ebextensions/**
cache:
  paths:
    - /root/.m2/**/*
